### ISSUE TITLE
USkeletalMeshComponent.Construct is not defined

### ISSUE THREAD

**Issue by EricDeng1001** [UnrealSharp/UnrealSharp#620]
<img width="1434" height="519" alt="Image" src="https://github.com/user-attachments/assets/e0972e9c-6087-41c7-bd72-32d3cd71f51a" />

while in docs: [helper method](https://www.unrealsharp.com/documentation/classes/helper-methods#construct-new-components)

**Comment by OlssonDev** [comment]
Should work now with the updated docs/code on latest. The reference path was wrong.

**Comment by EricDeng1001** [comment]
After pull latest commit, it's still not working? what am I doing wrong?

**Comment by EricDeng1001** [comment]
Sorry, it's working now
